# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://minha12.github.io/card_game/"

git_url = "https://github.com/minha12/card_game/tree/master/"

def custom_doc_links(name): return None
